<?php
function getBrands()
{
    return [
        "NIKE",
        "ADIDAS",
        "SKETCHERS",
        "PUMA",
        "REDTAPE",
        "SPARX",
        "BATA",
    ];
}

function total_brands()
{
    return count(getBrands());
}

function getProductType()
{
    return ['FORMAL', 'SPORT', 'SNEAKERS', 'RUNNIG'];
}

function getShoeFor()
{
    return ['Men', 'Women', 'Unisex', 'Kids'];
}

function BadWords()
{
    return [
        // Profanity
        'shit',
        'fcuk',
        'fuck',
        'bitch',
        'asshole',
        'dick',
        'piss',
        'cunt',
        'cocksucker',
        'motherfucker',
        'bullshit',
        'bastard',
        'prick',
        'twat',
        'slut',
        'whore',
        'cock',
        'assclown',
        'bitchass',
        'buttface',
        'cockwaffle',
        'dickhead',
        'douchecanoe',
        'douchewaffle',
        'dumbass',
        'dumbfuck',
        'fartknocker',
        'fucktard',
        'fuckwad',
        'jackass',
        'jagoff',
        'jerkoff',
        'kunt',
        'numbnuts',
        'pissface',
        'pissflaps',
        'shithead',
        'shitstain',
        'shitwad',
        'slutbag',
        'twatwaffle',
        'wankstain',

        // Sexual Content
        'jizz',
        'cum',
        'semen',
        'ejaculation',
        'deepthroat',
        'rimjob',
        'fisting',
        'pegging',
        'cuckold',
        'gangbang',
        'orgy',
        'blowjob',
        'cunnilingus',
        'fellatio',
        'anal',
        'vaginal',
        'masturbation',
        'dildo',
        'vibrator',
        'bukkake',
        'gloryhole',
        'scat',
        'golden shower',
        'bdsm',
        'bondage',
        'sadism',
        'masochism',
        'dominatrix',
        'submissive',
        'dominant',
        'kink',
        'fetish',
        'erotic',
        'sensual',
        'xxx',
        'nsfw',
        'anal beads',
        'anal fisting',
        'ass to mouth',
        'assplay',
        'banging',
        'bareback',
        'boobies',
        'boobs',
        'butt plug',
        'buttsex',
        'clit',
        'clit piercing',
        'clit ring',
        'clit stimulation',
        'cock ring',
        'cocktail weenie',

        // Hate Speech & Slurs
        'nigger',
        'chink',
        'spic',
        'faggot',
        'dyke',
        'retard',
        'tism',
        'cripple',
        'mongoloid',
        'kike',
        'gook',
        'raghead',
        'honky',
        'cracker',
        'wetback',
        'sandnigger',
        'camel jockey',
        'porch monkey',
        'jungle bunny',
        'coon',
        'spade',
        'wop',
        'dago',
        'mick',
        'kraut',
        'nip',
        'ching chong',
        'fuckboy',
        'fuckgirl',
        'shemale',
        'manwhore',
        'bimbo',
        'airhead',
        'gold digger',

        // Body Shaming & Bullying
        'fat',
        'skinny',
        'ugly',
        'disgusting',
        'worthless',
        'loser',
        'nobody likes you',
        'get a life',
        'waste of space',
        'cringe',
        'fake',
        'pig',
        'cow',
        'whale',
        'skeleton',
        'anorexic',
        'bulimic',
        'lardass',
        'tubby',
        'chubby',
        'beached whale',
        'beanpole',
        'twig',
        'chunky',
        'blubber',
        'greaseball',

        // Self-Harm & Suicide References
        'kill yourself',
        'suicide',
        'unalive',
        'sewer slide',
        'self harm',
        'cutting',
        'die',
        'hang yourself',
        'nobody cares',
        'go die',
        'off yourself',
        'end it all',
        'end yourself',
        'why are you alive',
        'your life is pointless',


        // Algospeak / Obfuscated Terms
        'seggs',
        'corn',
        'porn',
        'glizzy',
        'cheese pizza',
        'camping',
        'sussy',
        'baka',
        'simp',
        'leg booty',
        'nip nops',
        'mascara',
        'cornucopia',
        'panda express',
        'clock app',
        'bird app',
        'ouid',
        'fork',
        'grape',
        'spicy eggplant',
        'zaza',
        '420 friendly',
        'blinker hit',
        'gas pack',
        'sniff sniff',
        'tunnel time',
        'not alive',
        'unal1ve',
        'unal!ve',
        'unaliv3',
        'die in minecraft',

        // Spam & Scams
        'click this link',
        'free giveaway',
        'earn money fast',
        'dm me for details',
        'follow this account',
        'visit this site',
        'buy followers',
        'cheap likes',
        'work from home',
        'crypto scam',
        'limited time offer',
        'make quick cash',
        'winner selected',
        'exclusive deal',
        'guaranteed profit',
        'sign up now',
        'get rich quick',
        'subscribe for money',
        'win a free iPhone',
        'claim your prize',

        //Drug
        'weed',
        'pot',
        'marijuana',
        'ganja',
        'blunt',
        'joint',
        'spliff',
        'doobie',
        '420',
        'zaza',
        'greenery',
        'herb',
        'reefer',
        'chronic',
        'hash',
        'hashish',
        'bong',
        'pipe',
        'dab',
        'dabbing',
        'edibles',
        'high af',
        'stoned',
        'baked',
        'kush',
        'skunk',
        'shatter',
        'wax',
        'resin',
        'cart',
        'cartridge',
        'delta 8',
        'delta 9',
        'cannabis',
        'sativa',
        'indica',
        'THC',
        'CBD',

        'coke',
        'cocaine',
        'crack',
        'snow',
        'blow',
        'yayo',
        'white girl',
        'meth',
        'crystal',
        'ice',
        'glass',
        'speed',
        'uppers',
        'downers',

        'acid',
        'LSD',
        'shrooms',
        'mushrooms',
        'psychedelics',
        'trip balls',

        'lean',
        'sizzurp',
        'purple drank',
        'codeine',
        'promethazine',

        'xan',
        'xanax',
        'bars',
        'benzos',
        'valium',
        'klonopin',

        'opioid',
        'heroin',
        'dope',
        'smack',
        'H',
        'horse',

        'pill',
        'pills',
        'tabs',
        'roll',
        'rolling',
        'Molly',
        'MDMA',
        'ecstasy',

        //Terrorism
        'bomb',
        'bombing',
        'blow up',
        'blowup',
        'explode',
        'explosion',
        'suicide bomb',
        'suicide bombing',
        'terrorist',
        'terrorism',
        'ISIS',
        'Al-Qaeda',
        'Taliban',
        'martyrdom',
        'jihad',
        'terrorist attack',
        'hostage',
        'kidnap',
        'kidnapping',
        'shooting spree',
        'massacre',
        'killing spree',
        'slaughter',
        'execute',
        'execution',
        'behead',
        'beheading',
        'slit throat',
        'cut throat',
        'gunshot',
        'gunfire',
        'gun violence',
        'assault rifle',
        'AR-15',
        'AK-47',
        'bomb threat',
        'threaten to kill',
        'shoot someone',
        'mass shooting',
        'terrorist threat',
        'hostage situation',
        'chemical weapon',
        'bio weapon',
        'bioterrorism',
        'death threat',
        'killing',
        'slay',
        'slain',
        'assassinate',
        'assassination',
        'poison',
        'poisoning',
        'strangle',
        'strangling',
        'stab',
        'stabbing',
        'stabbed',
        'knives',
        'machete',
        'sword attack',
        'shoot up',
        'school shooting',
        'massacre',
        'wipe out',
        'wipe them out',
        'murder spree',
        'rampage',
        'violence',
        'violent',
        'beating',
        'bludgeon',
        'hitman',
        'hired gun',
        'gunman',
        'armed robbery',
        'armed assault',
        'hostage taker',
        'mass killing',
        'bloodbath',
        'spree killing',
        'death cult',
        'anarchy',
        'anarchist',
        'overthrow government',
        'kill the president',
        'kill the prime minister',
        'kill the mayor',
        'assaulting',
        'attacking',
        'harassing',
        'mob violence',
        'gang violence',
        'gang war',
        'terrorist group',
        'militant',
        'militant group',
        'mass execution',
        'torture',
        'torturing',
        'inhumane',
        'death penalty',
        'disembowel',
        'decapitate',
        'bombing campaign',
        'guerrilla warfare',

        //Mentally abuse
        'crazy',
        'insane',
        'psycho',
        'lunatic',
        'mental case',
        'schizo',
        'retarded',
        'spaz',
        'madman',
        'madwoman',
        'nutcase',
        'maniac',
        'basket case',
        'out of your mind',
        'mentally unstable',
        'unstable',
        'lose your mind',
        'broken mind',
        'mental breakdown',
        'youre worthless',
        'youre nothing',
        'nobody cares',
        'no one loves you',
        'youre stupid',
        'youre pathetic',
        'you dont matter',
        'youll never succeed',
        'failure',
        'hopeless',
        'worthless',
        'useless',
        'youre a burden',
        'everyone hates you',
        'nobody wants you here',
        'youre not good enough',
        'youre a disappointment',
        'loser',
        'youll never be anything',
        'youre just like your parents',
        'no one will ever love you',
        'give up',
        'end it all',
        'no one cares about you',
        'you dont deserve to live',
        'youre useless',
        'youre a piece of shit',
        'nothing but a failure',
        'your life is pointless',
        'youre weak',
        'youre broken',
        'youre nothing without me',
        'youre dumb',
        'youre a joke',
        'no one likes you',
        'youre a waste of space',
        'stop pretending',
        'youre not good enough for them',
        'youre not important',
        'youre too much to handle',
        'youre crazy to think anyone would like you',
        'youll always be alone',
        'youll never fit in',
        'youre a waste of time',
        'youll always fail',
        'you cant do anything right',
        'no one will ever trust you',
        'nobody believes you',
        'youre just like everyone else',
        'youre just a follower',
        'youre nothing special',
        'you dont deserve happiness',
        'you dont deserve love',
        'youll never be successful',
        'just give up already',
        'why are you even trying',
        'youll always be alone',
        'stop dreaming',
        'dont waste my time',
        'youre a coward',
        'youre weak-minded',
        'youre not strong enough',
        'stop pretending youre okay',
        'youre nothing but a waste',
        'shut up',
        'no one cares what you have to say',
        'youll never amount to anything',
        'youre so annoying',
        'youre just a disappointment',
        'stop acting like youre important',
        'just leave',
        'no one wants you around'
    ];
}